Update building-blocks.yml

diff --git a/.github/workflows/building-blocks.yml b/.github/workflows/building-blocks.yml
--- a/.github/workflows/building-blocks.yml
+++ b/.github/workflows/building-blocks.yml
@@ -1,21 +1,44 @@
 name: 01 - Building Blocks
 
-on: 
-  push:
+on: push
 
 jobs:
-  echo-hello:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Say hello
-        run: echo "Hello, World!"
+ 
+  hello:
 
-  echo-goodbye:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Successful step
-        run: |
-          echo "I will succeed"
-          exit 0
-      - name: Say goodbye
-        run: echo "Goodbye!"
+   runs-on: ubuntu latest
+
+   steps:
+
+    -run: echo "Hellow  -world"
+
+good bye:
+
+ runs-on: ubuntu-latest
+
+ steps:
+
+  # First step fails initally
+
+  - name: Failed step # First step
+
+    run: |
+
+     echo "I will fail"
+
+     exit 1
+
+   - name: Say gooodbye  # Second step
+   
+     run: echo "Good bye"
+
+    - name: Succeeding step (updated version) 
+      run: |
+
+        echo "This will now succeed"
+
+        exit 0
+        
+     
+
+ 
